platform :ios, '8.0'

target 'sdfd' do
use_frameworks!
pod 'AFNetworking'      # http
pod 'CocoaAsyncSocket'  # Socket
pod 'MJExtension'
pod 'SDWebImage'
pod 'Masonry'
pod 'MJRefresh'
pod 'YYKit'
pod 'BaiduMapKit'
pod 'JHChart'
pod 'FMDB/SQLCipher'             #数据库
pod 'ZLPhotoBrowser'


#   Debug模式下使用的一些辅助库,只在开发Target上面使用
pod 'Reveal-iOS-SDK', :configurations => ['Debug']

end

target 'mytodayWidge' do
use_frameworks!
pod 'AFNetworking'
end
