platform :ios, '7.0'

target 'sdfd' do

pod 'MJExtension'

pod 'AFNetworking'

pod 'Masonry'

pod 'MJRefresh'

pod 'MJPhotoBrowser'

pod 'YYKit'

end

target 'mytodayWidge' do

pod 'AFNetworking'

end
