platform :ios, '7.0'

target 'sdfd' do
pod 'AFNetworking'      # http
pod 'CocoaAsyncSocket'  # Socket
pod 'MJExtension'
pod 'SDWebImage'
pod 'Masonry'
pod 'MJRefresh'
pod 'YYKit'
pod 'BaiduMapKit'
end

target 'mytodayWidge' do
pod 'AFNetworking'
end
